environment/easystarter_web/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup')
]

environment/easystarter_web/concepts_storage_app/urls.py
from django.urls import path
from . import views

app_name = 'concepts_storage_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('concept/<slug:slug>', views.ConceptDetailView.as_view(), name='details'),
    path('keywords/<int:id>', views.get_concepts_base_on_keywords, name='keywords'),
    path('add', views.add_concept, name='add_concept'),
    path('contacts', views.contacts, name='contacts'),
    path('about', views.about, name='about'),
    path('team', views.team, name='team'),
]

environment/easystarter_web/easystarter_web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('', include('concepts_storage_app.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

environment/easystarter_web/concepts_storage_app/models.py
import datetime
import pytz

from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone
from django.utils.text import slugify

from ckeditor_uploader.fields import RichTextUploadingField

from .choices import *

utc = pytz.UTC


class Keywords(models.Model):
    class Meta:
        db_table = 'keywords'
    name = models.CharField(max_length=50, unique=True, verbose_name='Tags')

    def __str__(self):
        return self.name


class Concept(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=50, blank=True, unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Concept, self).save(*args, **kwargs)

    description = RichTextUploadingField(max_length=15000)
    status = models.CharField(max_length=50,
                              choices=STATUS, default='Draft')
    created = models.DateTimeField(auto_now_add=True)
    pub_date = models.DateTimeField('Publication date')

    category = models.CharField(max_length=50, blank=True, choices=CATEGORY)
    keywords = models.ManyToManyField(Keywords, related_name='keywords',
                                      related_query_name='keyword',
                                      verbose_name='Tags')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'publication date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently ?'

    def __str__(self):
        return self.title

    goal = models.IntegerField(default=0, validators=[MaxValueValidator(100000000), MinValueValidator(0)])
    pledge = models.IntegerField(default=0, validators=[MaxValueValidator(100000000), MinValueValidator(0)])

    def funded(self):
        if self.pledge == 0 or self.goal == 0:
            return 0
        else:
            return round((self.pledge/self.goal)*100, 2)

    backers_counter = models.IntegerField(default=0)
    days_to_go = models.IntegerField(choices=DAYS_TO_GO, default=30)

    def get_days_left(self):
        days = datetime.timedelta(days=self.days_to_go).days-(datetime.date.today() - self.pub_date.date()).days
        return days if days > 0 else 0

environment/easystarter_web/concepts_storage_app/forms.py
from django import forms

from .choices import *
from .models import Concept
from datetime import datetime
from ckeditor.widgets import CKEditorWidget


class ConceptForm(forms.Form):
    class Meta:

        model = Concept
        fields = ['title', 'description']

    title = forms.CharField(required=True, label='Title',
                            widget=forms.TextInput(attrs={'id': 'title'}))

    description = forms.CharField(widget=CKEditorWidget())

    date_now = datetime.now().date().strftime("%m/%d/%Y")
    pub_date = forms.CharField(required=True, label='Date of publication',
                               widget=forms.TextInput(attrs={'id': 'datepicker', 'width': '200',
                                                             'value': date_now}))

    category = forms.ChoiceField(required=True, label='Category', choices=CATEGORY,
                                 widget=forms.Select(attrs={'id': 'category'}), initial='')

    goal = forms.IntegerField(required=True, max_value=100000000, min_value=0, label='Goal',
                              widget=forms.TextInput(attrs={'aria-label': 'Amount (to the nearest dollar)',
                                                            'type': 'text',
                                                            'id': 'goal'}))

    days_to_go = forms.ChoiceField(required=True, choices=DAYS_TO_GO, label='Days to go',
                                   widget=forms.RadioSelect(attrs={'id': 'choice',
                                                                   'class': 'list-unstyled'}))


class MessageForm(forms.Form):
    name = forms.CharField(required=True, max_length=50,
                           widget=forms.TextInput(attrs={
                                                    'class': 'form-control col-md-8 col-sm-12 col-xs-12',
                                                    'id': 'Name',
                                                    'aria-describedby': 'nameHelp',
                                                    'placeholder': '',
                                                    'type': 'text'
                                                    }))

    email = forms.EmailField(required=True, max_length=50, label='Email',
                             widget=forms.EmailInput(attrs={
                               'class': 'form-control col-md-8 col-sm-12 col-xs-12',
                               'id': 'Email1',
                               'aria-describedby': 'emailHelp',
                               'placeholder': 'Enter',
                               'type': 'email'
                           }))

    phone = forms.CharField(required=True, label='Phone number',
                            widget=forms.TextInput(attrs={
                                                    'class': 'form-control col-md-8 col-sm-12',
                                                    'id': 'Phone',
                                                    'aria-invalid': 'false',
                                                    'placeholder': '+00000000000',
                                                    'type': 'tel',
                                                    'size':  '10',
                                                    'name': 'tel'
                               }))

    message = forms.CharField(required=True, max_length=1000,  label='Message',
                              widget=forms.Textarea(attrs={
                                   'class': 'form-control col-md-8 col-sm-12',
                                   'id': 'exampleFormControlTextarea1',
                                   'rows': '3'
                              }))

environment/easystarter_web/concepts_storage_app/views.py
from datetime import datetime

from django.conf import settings
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response, render
from django.core.mail import send_mail
from django.views import generic

from .models import Concept, Keywords
from .forms import ConceptForm, MessageForm


def index(request):
    concepts_storage = Concept.objects.all()
    keywords = Keywords.objects.all()
    return render_to_response('concepts_storage_app/index.html', {'concepts_storage': concepts_storage,
                                                                  'keywords': keywords})


def about(request):
    return render_to_response('concepts_storage_app/about.html')


def team(request):
    return render_to_response('concepts_storage_app/team.html')


def contacts(request):
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            phone = form.cleaned_data['phone']
            message = form.cleaned_data['message']
        send_mail('Message from ' + name,
                  'Phone: ' + phone + "\n" + "Email: " + email + "\n" + message,
                  email, [settings.EMAIL_HOST_USER])
        return HttpResponse('Thanks for feedback')
    else:
        form = MessageForm()
    return render(request, 'concepts_storage_app/contacts.html', {'form': form})


class ConceptDetailView(generic.DetailView):
    model = Concept
    template_name = 'concepts_storage_app/details.html'

    def get_context_data(self, **kwargs):
        context = super(ConceptDetailView, self).get_context_data(**kwargs)
        context['slug'] = self.kwargs['slug']
        context['keywords'] = Keywords.objects.all()
        return context


def add_concept(request):
    if request.method == 'POST':
        form = ConceptForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            pub_date = datetime.strptime(form.cleaned_data['pub_date'], '%m/%d/%Y')
            goal = form.cleaned_data['goal']
            days_to_go = form.cleaned_data['days_to_go']
            Concept.objects.create(
                title=title,
                description=description,
                pub_date=pub_date,
                goal=goal,
                days_to_go=days_to_go
            ).save()
            return HttpResponseRedirect('/')
    else:
        form = ConceptForm()
    return render(request, 'concepts_storage_app/form.html', {'form': form})


def get_concepts_base_on_keywords(request, id):
    kwargs = {}

    kwargs['keywords'] = Keywords.objects.all()
    kwargs['keyw_s'] = Keywords.objects.get(id=id)
    kwargs['concepts'] = Concept.objects.filter(keywords__name__exact=kwargs['keyw_s'])
    return render(request, 'concepts_storage_app/keypage.html', kwargs)

environment/easystarter_web/concepts_storage_app/templates/concepts_storage_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'concepts_storage_app/img/favicon.ico' %}"/>
    <!-- bootstrapcdn style-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <!-- fontawesome style-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

    <!-- bootstrapcdn & jquery script-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

    <!-- main style --->
    <link rel="stylesheet" href="{% static 'concepts_storage_app/css/contact.css' %}">
    <link rel="stylesheet" href="{% static 'concepts_storage_app/css/homepage.css' %}">
    <link rel="stylesheet" href="{% static 'concepts_storage_app/css/manage_project.css' %}">
    <link rel="stylesheet" href="{% static 'concepts_storage_app/css/new_project.css' %}">
    <link rel="stylesheet" href="{% static 'concepts_storage_app/css/project_author.css' %}">
    <link rel="stylesheet" href="{% static 'concepts_storage_app/css/team.css' %}">
    <link rel="stylesheet" href="{% static 'concepts_storage_app/css/about.css' %}">
    <link rel="stylesheet" href="{% static 'concepts_storage_app/css/form.css' %}">


    <!-- script main -->
    <script src="{% static 'concepts_storage_app/js/script.js' %}"></script>

    <!-- fonts -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
    {% block head %}
    {% endblock %}
</head>
<body>
<header class="header">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-xs-12">
                <button type="submit" class="btn btn-primary buttonPrm"><span>Explore</span></button>
                <button onclick="window.location='{% url 'concepts_storage_app:add_concept' %}'"
                    type="submit" class="btn btn-primary buttonPrm" ><span>Start project</span>
                </button>
            </div>
            <div class="col-md-4 col-xs-12"><a href="{% url 'concepts_storage_app:index' %}"><img src="{% static 'concepts_storage_app/img/logo.png' %}" alt="Logo"></a></div>
            <div class="col-md-4 col-xs-12">
                <div class="input-group stylish-input-group">
                    <span class="buttonPrm"><input type="text" class="form-control search-input"  placeholder="Search" ></span>
                </div>
                <button type="button" class="btn btn-primary buttonSingIn" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo"><span><i class="fas fa-power-off"></i>Sing in</span></button>
            </div>
        </div>
    </div>
    <!--<div>-->
        <!--<h4>Tags:</h4>-->
        <!--{% for keyword in keywords %}-->
            <!--<a href="{% url 'concepts_storage_app:keywords' id=keyword.id %}">{{ keyword }} </a>-->
        <!--{% if not forloop.last %}, {% endif %}-->
        <!--{% endfor %}-->
    <!--</div>-->
</header>
<main>
    {% block content %}
    {% endblock %}
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Sign in</h5>
            </div>
            <div class="modal-body">
                <form class="form-From-Contact">
                    <div class="form-group">
                        <label class="col-md-4 col-sm-12 col-xs-12" for="Name">User name:</label>
                        <input type="text" class="form-control col-md-8 col-sm-12 col-xs-12" id="Name" aria-describedby="nameHelp">
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-sm-12" for="Pass">Password:</label>
                        <input type="text" name="pass" class="form-control col-md-8 col-sm-12" id="Pass" >
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-sm-12" for="Signup">Not registered yet???</label>
                        <a href="{% url 'accounts:signup' %}" id="Signup">SignUp</a>
                    </div>
                    <!--<div class="form-group">-->
                        <!--<label class="col-md-4 col-sm-12" for="Email1">E-Mail:</label>-->
                        <!--<input type="email" class="form-control col-md-8 col-sm-12 col-xs-12" id="Email1" aria-describedby="emailHelp" >-->
                    <!--</div>-->
                    <!--<div class="form-group">-->
                        <!--<label class="col-md-4 col-sm-12" for="ResPass">Re-enter password:</label>-->
                        <!--<input type="text" name="respass" class="form-control col-md-8 col-sm-12" id="ResPass" >-->
                    <!--</div>-->
                    <!--<div class="form-group">-->
                        <!--<label class="col-md-4 col-sm-12"></label>-->
                        <!--<div class="col-md-8 col-sm-12 block-bottom">-->
                            <!--<div class="row">-->
                                <!--<div class="col-md-6 col-xs-12">-->
                                    <!--<div class="row">-->
                                        <!--By signing up, you agree to our terms of use and privacy policy-->
                                    <!--</div>-->
                                <!--</div>-->
                                <!--<div class="col-md-6 col-xs-12">-->
                                    <!--<div class="row textRight">-->
                                        <!--<button type="submit" class="btn btn-primary Send">Create account</button>-->
                                    <!--</div>-->
                                <!--</div>-->
                            <!--</div>-->
                        <!--</div>-->
                    <!--</div>-->
                    <!--<div class="form-group">-->
                        <!--<label class="col-md-4 col-sm-12"></label>-->
                        <!--<div class="col-md-8 col-sm-12 block-bottom">-->
                            <!--<div class="row">-->
                                <!--<div class="col-md-6 col-xs-12">-->
                                    <!--<div class="row">-->
                                        <!--Log in using services:-->
                                    <!--</div>-->
                                <!--</div>-->
                                <!--<div class="col-md-6 col-xs-12">-->
                                    <!--<div class="row textRight">-->
                                        <!--<div class="form-group button"><button type="submit" class="btn btn-primary Send">Send</button></div>-->
                                    <!--</div>-->
                                <!--</div>-->
                            <!--</div>-->
                        <!--</div>-->
                    <!--</div>-->
                </form>
            </div>
        </div>
    </div>
</div>
</main>
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-xs-12">
                <h3 class="Title-footer">About us</h3>
                <ul class="footer-list">
                    <li><a href="{% url 'concepts_storage_app:about' %}">What Is EasyStarter?</a></li>
                    <li><a href="{% url 'concepts_storage_app:team' %}">Team</a></li>
                    <li><a href="{% url 'concepts_storage_app:contacts' %}">Contacts</a></li>
                </ul>
            </div>
            <div class="col-md-4 col-xs-12">
                <h3 class="Title-footer">Help center</h3>
                <ul class="footer-list">
                    <li><a href="{% url 'concepts_storage_app:about' %}">How Does It Work?</a></li>
                    <li><a href="{% url 'concepts_storage_app:about' %}">About Crowdfunding</a></li>
                    <li><a href="{% url 'concepts_storage_app:about' %}">Questions And Answers</a></li>
                    <li><a href="{% url 'concepts_storage_app:about' %}">Our Rules</a></li>
                </ul>
            </div>
            <div class="col-md-4 col-xs-12">
                <h3 class="Title-footer">Categories</h3>
                <div class="d-flex justify-content-between">
                    <ul class="col-md-4 col-xs-12 footer-list">
                        <li><a href="#">Movie</a></li>
                        <li><a href="#">Design</a></li>
                        <li><a href="#">Food</a></li>
                        <li><a href="#">Theater</a></li>
                        <li><a href="#">IT</a></li>
                    </ul>
                    <ul class="col-md-4 col-xs-12 footer-list">
                        <li><a href="#">Music</a></li>
                        <li><a href="#">Printing</a></li>
                        <li><a href="#">Games</a></li>
                        <li><a href="#">Technology</a></li>
                        <li><a href="#">Ecology</a></li>
                        <li><a href="#">Design</a></li>
                    </ul>
                    <ul class="col-md-4 col-xs-12 footer-list">
                        <li><a href="#">Photography</a></li>
                        <li><a href="#">Art</a></li>
                        <li><a href="#">Fashion</a></li>
                        <li><a href="#">Sport</a></li>
                        <li><a href="#">Innovation</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-xs-12">
                <div class="social-block-footer">
                    <a href="https://www.instagram.com"><i class="fab fa-instagram"></i></a>
                    <a href="https://telegram.org"><i class="fab fa-telegram-plane"></i></a>
                    <a href="https://twitter.com"><i class="fab fa-twitter"></i></a>
                </div>
            </div>
            <div class="col-md-4 col-xs-12">
                <p>EasyStarter.com.ua © 2018</p>
            </div>
        </div>
    </div>
</footer>
</body>
</html>

environment/easystarter_web/concepts_storage_app/templates/concepts_storage_app/details.html
{% extends 'concepts_storage_app/base.html' %}
{% load static %}
{% block title %}{{ concept.title| truncatewords:3 }}{% endblock %}
{% block header %}
{% endblock %}
{% block content %}
<section class="project-author">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-xs-12">
                <div class="wrapper-author-01">
                    <h1 class="Title01 text-left text-uppercase">{{ concept.title}}</h1>
                    <!--<p class="author-line">-->
                        <!--<span>Lorem</span>-->
                    <!--</p>-->
                    <p class="position"><span>Author</span></p>
                    <p>Created: {{ concept.created|date:"Y-M-d" }}</p>
                    <p>Published: {{ concept.pub_date|date:"Y-M-d" }}</p>
                    <p class="text-right"><a href="{% url 'concepts_storage_app:index' %}" class="buttonPrm">Go Back</a></p>
                </div>
                <div class="wrapper-author-02 d-flex">
                    <div class="col-md-5 col-xs-12">
                        <div class="row">
                            <p class="visitors">
                                <img src="{% static 'concepts_storage_app/img/people.png' %}" alt="">
                                <span>{{ concept.backers_counter }} backers funded {{ concept.funded }}% of the project</span>
                            </p>
                            <p class="times">
                                <img src="{% static 'concepts_storage_app/img/time.png' %}" alt="">
                                <span>{{ concept.get_days_left }} days to go</span>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-7 col-xs-12">
                        <div class="row">
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="max-width:{{ concept.funded }}%">
                                    <span class="title">{{ concept.pledge }}$ / {{ concept.goal }}$</span>
                                </div>
                            </div>
                            <div class="row-wrapper d-flex justify-content-between">
                                <button onclick="window.location='{% url 'concepts_storage_app:index' %}'"
                                        type="submit" class="btn btn-primary buttonPrm"><span>Explore</span></button>
                                <button onclick="window.location='{% url 'concepts_storage_app:add_concept' %}'"
                                        type="submit" class="btn btn-primary buttonPrm"><span>Start project</span></button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="wrapper-author-03">
                    {% autoescape off %}{{ concept.description}}{% endautoescape %}
                </div>
            </div>
            <div class="col-md-4 col-xs-12">
                <img src="{% static 'concepts_storage_app/img/img.png' %}"  class="width-100" alt="">
                <div class="sidebar">
                    <h3 class="text-right text-uppercase">Rewards</h3>
                    <div class="wrapper-author-04">
                        <div class="block-wrapper">
                            <h4 class="text-uppercase">Reward Lev.1</h4>
                            <p>Pledge $10 or more</p>
                            <p>Get a sticker</p>
                            <p>Get the sticker with the company logo</p>
                        </div>
                        <div class="block-wrapper">
                            <h4 class="text-uppercase">Reward Lev.2</h4>
                            <p>Pledge $25 or more</p>
                            <p>Get a keychain</p>
                            <p>Get the keychain with the company logo</p>
                        </div>
                        <div class="block-wrapper">
                            <h4 class="text-uppercase">Reward Lev.3</h4>
                            <p>Pledge $50 or more</p>
                            <p>Get a bag</p>
                            <p>Get the bag with the company logo</p>
                        </div>
                        <div class="block-wrapper">
                            <h4 class="text-uppercase">Reward Lev.4</h4>
                            <p>Pledge $75 or more</p>
                            <p>Get a secret box</p>
                            <p>Get the special box with a lot of things from the company</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

environment/easystarter_web/concepts_storage_app/templates/concepts_storage_app/index.html
{% extends "concepts_storage_app/base.html" %}
{% load static %}
{% block header %}
{% endblock %}
{% block content %}
        <div class="banner">
            <img src="{% static 'concepts_storage_app/img/banner1.png' %}" alt="">
            <div class="fon-banner"></div>
            <div class="container">
                <div class="Textwrapper">
                    <h2 class="Text01">Welcome to EasyStarter!</h2>
                    <p class="Text01">We are the community who helps to implement your ideas in real life</p>
                    <p class="Text01">We create the future together</p>
                    <p class="Text02"><a href="{% url 'concepts_storage_app:about' %}">Click here to learn more</a></p>
                </div>
            </div>
        </div>
        <section id="Template01">
            <div class="container">
                <h1 class="MainTitle"><span>Projects</span></h1>
                    <div class="row">
                        {% if concepts_storage %}
                        {% for concept in concepts_storage %}
                                <div class="col-md-4 col-xs-12">
                                    <div class="border-block">
                                        <div class="background-block">
                                            <h3 class="title-project">{{ concept.title | truncatechars:50 }}</h3>
                                            <p class="author-line">
                                                <span>Author: Mr. Smith</span>
                                                <!--<span>Status: {{ concept.status }}</span>-->
                                            </p>
                                            <p class="category">
                                                <span>Category: {{ concept.category }}</span>
                                            </p>
                                            <!--<p>-->
                                                <!--<span>Created: {{ concept.created|date:"Y-M-d" }}</span>-->
                                                <!--<span>Published: {{ concept.pub_date|date:"Y-M-d" }}</span>-->
                                            <!--</p>-->
                                            <p>
                                                <img src="{% static 'concepts_storage_app/img/img.png' %}" class="imageMain" alt="Img">
                                            </p>
                                            <div class="textProject">{% autoescape off %}{{ concept.description|truncatechars:300 }}{% endautoescape %}</div>
                                            <p class="visitors">
                                                <img src="{% static 'concepts_storage_app/img/people.png' %}" alt="">
                                                <span>{{ concept.backers_counter }} backers funded {{ concept.funded }}% of the project</span>
                                            </p>
                                            <p class="times">
                                                <img src="{% static 'concepts_storage_app/img/time.png' %}" alt="">
                                                <span>{{ concept.get_days_left }} days to go</span>
                                            </p>
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="max-width:{{ concept.funded }}%">
                                                    <span class="title">{{ concept.pledge }}$ / {{ concept.goal }}$</span>
                                                </div>
                                            </div>
                                            <p style="text-align: center;">
                                                <button class="buttonPrm" onclick="window.location='{% url 'concepts_storage_app:details' slug=concept.slug %}'">
                                                    <span>View Detail</span>
                                                </button>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            {% endif %}
                    </div>
                    <div class="col-md-12 col-xs-12">
                        <div class="background-block addBlock">
                            <p><img src="{% static 'concepts_storage_app/img/logo-title.png' %}" alt=""></p>
                            <p><img src="{% static 'concepts_storage_app/img/title01.png' %}" alt=""></p>
                            <p class="text-center"><a href="{% url 'concepts_storage_app:add_concept' %}" class="buttonPrm">Start</a></p>
                        </div>
                    </div>
            </div>
        </section>
{% endblock %}